name: release flask-app package

on:
  push:
    branches:
      - main
      - add-actions-for-docker-container-registory

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login GitHub Docker Registory
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/hirokiw/flask-app:latest
